version: "3.9"

services:
  db:
    container_name: ${CONTAINER_DB_NAME}
    image: ${DB_IMAGE:-mariadb}:${DB_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}     


  wordpress:
    depends_on:
      - db
    container_name: ${CONTAINER_SITE_NAME}
    image: ${SITE_IMAGE:-wordpress}:${SITE_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
      - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_DB_NAME}:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}

  nginx:
    # container_name: nginx
    restart: always
    image: "nginx:1.19.10"  
    ports:
      - "80:8080"
    volumes:
      - ./nginx-config-files/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-config-files/app.nginx.template:/etc/nginx/templates/app.nginx.template
    environment:      
      WORDPRESS_HOST: ${CONTAINER_SITE_NAME}:80
    depends_on:
      - db
      - wordpress


volumes:
  db_data: {}
  wordpress_data: {}