version: "3.9"
services:
  phpmyadmin:    
    container_name: phpmyadmin-container
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 64M
    expose:
      - 80
    ports:
      - "9000:80"           
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin_rtr_local.entrypoints=phpmyadmin"
      - "traefik.http.routers.phpmyadmin_rtr_local.rule=Host(`phpmyadmin.${LOCAL_1}`, `phpmyadmin.${LOCAL_2}`)"
      - "traefik.http.routers.phpmyadmin_rtr.entrypoints=phpmyadmin"
      - "traefik.http.routers.phpmyadmin_rtr.rule=Host(`phpmyadmin.${EXT_ENDPOINT1}`, `phpmyadmin.${EXT_ENDPOINT2}`, `phpmyadmin.${EXT_ENDPOINT3}`)"

  wordpress:    
    container_name: ${CONTAINER_SITE_NAME}
    image: wordpress:5.6
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
      - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini     
    expose:  # new
      - 80    
    environment:
      WORDPRESS_DB_HOST: ${PMA_HOST}:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress_http.entrypoints=web"
      - "traefik.http.routers.wordpress_http.rule=Host(`${LOCAL_1}`, `${LOCAL_2}`, `${EXT_ENDPOINT1}`, `${EXT_ENDPOINT2}`, `${EXT_ENDPOINT3}`)"      
      - "traefik.http.routers.wordpress_https.entrypoints=websecure"
      - "traefik.http.routers.wordpress_https.tls.certresolver=teeresolver"
      - "traefik.http.routers.wordpress_https.rule=Host(`${EXT_ENDPOINT1}`, `${EXT_ENDPOINT2}`, `${EXT_ENDPOINT3}`)"

  traefik:
    image: "traefik:latest"
    container_name: "traefik-container"
    restart: always
    command:
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8000:8000"
      - "3306:3306"
    depends_on:      
      - wordpress
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/.htpasswd:/.htpasswd
      # - ./traefik/acme.json:/acme.json
      # - ./traefik/configurations:/configurations
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${LOCAL_1}`, `traefik.${LOCAL_2}`,`traefik.${EXT_ENDPOINT1}`, `traefik.${EXT_ENDPOINT2}`, `traefik.${EXT_ENDPOINT3}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/.htpasswd"
      # - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      # - "traefik.http.routers.traefik-secure.rule=Host(`traefik.jrtec.io`)"
      # - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
      # - "traefik.http.routers.traefik-secure.service=api@internal"     

volumes:
  db_data: {}
  wordpress_data: {}