api:
  dashboard: true
  # insecure: true # Don't do that in production

# Definici칩n de los entrypoints
entryPoints:
  web:
    address: :80
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure

  websecure:
    address: :443
  #   http:
  #     middlewares:
  #       - secureHeaders@file
  #     tls:
  #       certResolver: letsencrypt

# Proveedores: Docker y configuraci칩n din치mica mediante provider de tipo file.
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  # file:
  #   filename: /configurations/dynamic.yml

# Configuraci칩n Let's Encrypt que usaremos en el entrypoint websecure
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: jrtecweb2021@gmail.com
#       storage: /acme.json
#       keyType: EC384
#       httpChallenge:
#         entryPoint: web

metrics:
  datadog:
    addEntryPointsLabels: true
    address: datadog-agent:8125

tracing:
  datadog:
    localAgentHostPort: datadog-agent:8126

log:
  filePath: "/traefik/logs/traefik.log"
  format: json

accessLog:
  filePath: "/traefik/logs/access.log"